// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXRbZ4KVMNA05Xjoe5EAJBHSzqTypzbdA',
    appId: '1:125598521875:web:3e9fac96e2508ea71e3de6',
    messagingSenderId: '125598521875',
    projectId: 'maleva-spins',
    authDomain: 'maleva-spins.firebaseapp.com',
    storageBucket: 'maleva-spins.firebasestorage.app',
    measurementId: 'G-M9S0MGXY70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCozE_1gmGuR6D_MkAl03xX0kp3Dylzhkk',
    appId: '1:1090635195563:android:595b46afad1e7e8a3183ee',
    messagingSenderId: '1090635195563',
    projectId: 'malevaspins',
    storageBucket: 'malevaspins.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPFhJy6PSLW1cyETJHP2a38ISA_GOB5SY',
    appId: '1:125598521875:ios:787cb214f21df7f91e3de6',
    messagingSenderId: '125598521875',
    projectId: 'maleva-spins',
    storageBucket: 'maleva-spins.firebasestorage.app',
    iosBundleId: 'com.example.malevaSpins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPFhJy6PSLW1cyETJHP2a38ISA_GOB5SY',
    appId: '1:125598521875:ios:787cb214f21df7f91e3de6',
    messagingSenderId: '125598521875',
    projectId: 'maleva-spins',
    storageBucket: 'maleva-spins.firebasestorage.app',
    iosBundleId: 'com.example.malevaSpins',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXRbZ4KVMNA05Xjoe5EAJBHSzqTypzbdA',
    appId: '1:125598521875:web:86c40cad6edd46091e3de6',
    messagingSenderId: '125598521875',
    projectId: 'maleva-spins',
    authDomain: 'maleva-spins.firebaseapp.com',
    storageBucket: 'maleva-spins.firebasestorage.app',
    measurementId: 'G-3FN7XHVVH7',
  );
}