// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBltxSx53oMP3K5Vl3vKb3J8JOJmYhSFjI',
    appId: '1:1090635195563:web:1b0c783710a0afa43183ee',
    messagingSenderId: '1090635195563',
    projectId: 'malevaspins',
    authDomain: 'malevaspins.firebaseapp.com',
    storageBucket: 'malevaspins.firebasestorage.app',
    measurementId: 'G-S0VQ20ZZPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCozE_1gmGuR6D_MkAl03xX0kp3Dylzhkk',
    appId: '1:1090635195563:android:595b46afad1e7e8a3183ee',
    messagingSenderId: '1090635195563',
    projectId: 'malevaspins',
    storageBucket: 'malevaspins.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDLxhvZuIX7DEUtnZNj9KpD_7X-FlJSFU',
    appId: '1:1090635195563:ios:bd248718f1d7430d3183ee',
    messagingSenderId: '1090635195563',
    projectId: 'malevaspins',
    storageBucket: 'malevaspins.firebasestorage.app',
    iosBundleId: 'com.example.malevaSpins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDLxhvZuIX7DEUtnZNj9KpD_7X-FlJSFU',
    appId: '1:1090635195563:ios:bd248718f1d7430d3183ee',
    messagingSenderId: '1090635195563',
    projectId: 'malevaspins',
    storageBucket: 'malevaspins.firebasestorage.app',
    iosBundleId: 'com.example.malevaSpins',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBltxSx53oMP3K5Vl3vKb3J8JOJmYhSFjI',
    appId: '1:1090635195563:web:c7b4bf0102c5496a3183ee',
    messagingSenderId: '1090635195563',
    projectId: 'malevaspins',
    authDomain: 'malevaspins.firebaseapp.com',
    storageBucket: 'malevaspins.firebasestorage.app',
    measurementId: 'G-CVJSEC3T86',
  );

}