name: Build APK

on:
  push:
    branches:
      - master  

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Criar .env
        run: |
          echo "CALLBACKSCHEME=${{ secrets.CALLBACKSCHEME }}" >> .env
          echo "CONSUMERKEY=${{ secrets.CONSUMERKEY }}" >> .env
          echo "CONSUMERSECRET=${{ secrets.CONSUMERSECRET }}" >> .env

      - name: Instalar dependências
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
